### ISSUE TITLE
Very nice effect！But，What should I do with the color on the corner ？

### ISSUE THREAD

**Issue by shmen** [markuslerner/THREE.BlurredLine#7]
![image](https://user-images.githubusercontent.com/30108864/148037136-f9196422-806f-4483-ab08-77b55aed6ff7.png)

**Comment by markuslerner** [comment]
Hi, the start and end gradient ist not implemented yet. I can hopefully do that in the next few weeks. I have used a lineWidthModifier and blurWidthModifier function so far in order to reduce the width in the beginning and the end.

**Comment by markuslerner** [comment]
Unfortunately I currently have no capacities to implement that. I also feel that the blur should be re-written using a shader. Contributions welcome. :)
